version: "3"

services:
  javaee8-service:
    build:
      context: .
    image: javaee8-service:1.0.1
    ports:
    - "8080:8080"
    networks:
    - jee8net
    labels:
      kompose.service.type: loadbalancer
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 640M
        reservations:
          memory: 640M

  message-queue:
    image: rmohr/activemq:5.15.6
    expose:
    - "61616"       # the JMS port
    - "1883"        # the MQTT port
    - "5672"        # the AMQP port
    ports:
    - "8161:8161"   # the admin web UI
    networks:
    - jee8net
    labels:
      kompose.service.type: nodeport
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 512M

  postgres-db:
    image: "postgres:9.6.3"
    environment:
    - POSTGRES_USER=javaee8
    - POSTGRES_PASSWORD=12qwasyx
    - POSTGRES_DB=weather
    ports:
    - "5432:5432"
    networks:
    - jee8net
    labels:
      kompose.service.type: nodeport
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 128M

  # openapi-gui:
  #   image: mermade/openapi-gui
  #   ports:
  #   - "3000:3000"
  #   networks:
  #   - jee8net

networks:
  jee8net:
    driver: bridge
